Save as catalogue item #105
ral-facilities/inventory-management-system pull request #106
Opened 2023-10-24 14:09 UTC by joshuadkitenge

## Description

Add a save as button to each catalogue item which populates form with the values and allows the user to edit it.   

## Testing instructions

- [ ] Test that unique names are create in form e.g. test_copy 
- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking

closes #105

2023-11-10 08:43 UTC, joelvdavies requested changes
Looks good, just needs some unit tests to increase the coverage, and merge with develop as `web_url` -> `url` in manufacturer which causes an error on the `trim()` when I attempt to save.

2023-11-13 08:58 UTC, joelvdavies approved these changes

2023-11-14 15:39 UTC, VKTB submitted a review, later dismissed

2023-11-14 16:00 UTC, joelvdavies approved these changes

2023-11-14 16:06 UTC, merged