Edit Dialog for Images
ral-facilities/inventory-management-system pull request #1151
Opened 2024-12-11 10:10 UTC by asuresh-code

## Description

#1075 

## Testing instructions

Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking

closes #1075

2024-12-17 09:33 UTC, joshuadkitenge commented on src/common/images/editFileDialog.component.tsx
> +}
Can use use a discrimination union for the type. to distinguish between image and attachments type  
https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html

2024-12-17 09:33 UTC, joshuadkitenge commented
Can you amove the editFileDialog out of common/images to common/ please

2025-01-06 20:27 UTC, rowan04 reviewed
just some grammar rewriting for the if test descriptions. The rest of the code looks good I think but I haven't tested the functionality.

2025-01-06 20:27 UTC, rowan04 commented on cypress/e2e/with_mock_data/items.cy.ts
> +    it('Required fields that are cleared are not allowed and show error message', () => {
```suggestion
    it('shows error message when required fields are cleared', () => {
```

2025-01-09 13:22 UTC, joshuadkitenge requested changes

2025-01-15 12:46 UTC, rowan04 commented
why does one of the images not show for me? it seems to happen for any catalogue item, always the 3rd image. I assume its not to do with your changes here but maybe you know why
![image](https://github.com/user-attachments/assets/e203aa98-b918-446f-ab17-3b0b8a6703c3)

2025-01-15 13:54 UTC, joshuadkitenge commented
> why does one of the images not show for me? it seems to happen for any catalogue item, always the 3rd image. I assume its not to do with your changes here but maybe you know why ![image](https://private-user-images.githubusercontent.com/90393428/403419776-e203aa98-b918-446f-ab17-3b0b8a6703c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5NDk0MzYsIm5iZiI6MTczNjk0OTEzNiwicGF0aCI6Ii85MDM5MzQyOC80MDM0MTk3NzYtZTIwM2FhOTgtYjkxOC00NDZmLWFiMTctM2IwYjhhNjcwM2MzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE1VDEzNTIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNDI2ODY0ZjZhNDQxMjhkNjU0NGUzZGEzMTJhOGE5YWEyM2M2NDczNjdiNzdlOTI4YjIxNmU5NjMxYjg4OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8R6Sbbj_b2ApRikfnehtKJPTUhNVTLOkaHeZvMqY-Oc)

That is on purpose for the unit and e2e test with the mock data

2025-01-16 15:07 UTC, joshuadkitenge commented
Can you add the end adornment to the uppy upload dialog file in this pr please

2025-01-16 16:08 UTC, rowan04 commented on cypress/e2e/with_mock_data/items.cy.ts
> +    it('shows error when no fields have been changed', () => {
```suggestion
    it('shows error message when no fields have been changed', () => {
```
apologies i know i changed it to this the first time :)

2025-01-17 13:51 UTC, joshuadkitenge commented
> Can you add the end adornment to the uppy upload dialog file in this pr please

Can this be done for both dialog images and attachments

2025-01-22 09:43 UTC, joshuadkitenge requested changes

2025-01-23 16:22 UTC, asuresh-code commented
- Currently the `uppy.utils.tsx` does not have a test file. Is this something that needs to be changed?
- I'm unable to view the codecov report to see what lines are missing; Is this an issue others are having?
- The implementation for checking if dark mode is enabled is the same as what SciGateway does. I tried using the light-dark implemntation seen [here](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark), but it did not work (I'm not sure why).

2025-01-24 09:34 UTC, joshuadkitenge commented
> * Currently the `uppy.utils.tsx` does not have a test file. Is this something that needs to be changed?
> 
>     * I'm unable to view the codecov report to see what lines are missing; Is this an issue others are having?
> 
>     * The implementation for checking if dark mode is enabled is the same as what SciGateway does. I tried using the light-dark implemntation seen [here](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark), but it did not work (I'm not sure why).

3. Look a the third button point for how to check if it ligh or dark mode https://github.com/ral-facilities/inventory-management-system/pull/1151#discussion_r1923969268

2025-01-24 12:41 UTC, joshuadkitenge requested changes
> * Currently the `uppy.utils.tsx` does not have a test file. Is this something that needs to be changed?
> 
>     * I'm unable to view the codecov report to see what lines are missing; Is this an issue others are having?
> 
>     * The implementation for checking if dark mode is enabled is the same as what SciGateway does. I tried using the light-dark implemntation seen [here](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark), but it did not work (I'm not sure why).
1. The contents of uppy.utils.tsx do not need direct testing, as they are indirectly tested through other components or functions that utilize this file. The current contents of this file is never used as a standalone module, so testing its integration with the uppy is what’s important. However, this statement applies only to the current contents of the file. Any new functionality added in the future should be evaluated to determine if direct testing is necessary.
2. i had the same issue logging into codecov solved the issue for me. You should also be able to see the report local when you run the tests  
3. Look a the third button point for how to check if it light or dark mode https://github.com/ral-facilities/inventory-management-system/pull/1151#discussion_r1923969268.
3.1.  Do the same implemenation as uppy does.

2025-01-24 13:22 UTC, joshuadkitenge commented on src/common/images/uploadImagesDialog.component.tsx
> +          },
> * As the metafields for attachements and images are the same can you make a general object to set them both

you have current done this for just the name this should be done the whole metafields

2025-01-27 09:04 UTC, asuresh-code commented
> 3. Look a the third button point for how to check if it light or dark mode [Edit Dialog for Images #1151 (comment)](https://github.com/ral-facilities/inventory-management-system/pull/1151#discussion_r1923969268).
>    3.1.  Do the same implemenation as uppy does.

I can see that uppy creates a CSS class that conditionally sets the style based on a variable data-uppy-theme
![image](https://github.com/user-attachments/assets/1601f95f-9899-49fd-b219-4b45d190b221)
I could copy the CSS class they use and style the div element with that when the input element is focussed, which would mean I wouldn't need the condition to check if it's in dark mode. However this would require a separate CSS file in our repo. I can't use the exact same styling (import style from uppy somehow), because it would only apply when div is focussed, whilst I need it to apply when input is focussed.

 _I did try and see if there was any way to trick the div element's CSS into think its being focussed, without actually focussing on it, but I couldn't find anything that worked_

_CSS also has the `focus-within` property which would be perfect for this case, since the input elem being triggered would cause any styling on the div with this as a condition to be applied, but again this would require changing the CSS class, which I don't think you can do using inline CSS, so it would also require a separate CSS stylesheet in our repo._

I tried passing the theme prop from the dashboard to the render function, however it does not update when I switch themes.

I think if I want to do uppy's implementation I would need to either: a. create a separate CSS file to create a CSS class in the same way uppy does, or b. use data-uppy-theme as the condition on whether it is dark (however it gets this from theme prop, which I also passed to my function, but it does not mutate).

2025-01-27 10:28 UTC, joshuadkitenge commented
> > 3. Look a the third button point for how to check if it light or dark mode [Edit Dialog for Images #1151 (comment)](https://github.com/ral-facilities/inventory-management-system/pull/1151#discussion_r1923969268).
> >    3.1.  Do the same implemenation as uppy does.
> 
> I can see that uppy creates a CSS class that conditionally sets the style based on a variable data-uppy-theme ![image](https://private-user-images.githubusercontent.com/69875854/406468341-1601f95f-9899-49fd-b219-4b45d190b221.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc5NzIwMDcsIm5iZiI6MTczNzk3MTcwNywicGF0aCI6Ii82OTg3NTg1NC80MDY0NjgzNDEtMTYwMWY5NWYtOTg5OS00OWZkLWIyMTktNGI0NWQxOTBiMjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTI3VDA5NTUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5NzZhMDE4ZTc4YmI0MjNiZmQ1ODA3ZTFhNGM2ZDc3NjI4MjcyZTEzYjRiZWRhMzM2MzZkZDIzM2JkZjQ2YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mewqg1umwk7Noy2BhfQ54kAJI4h-0y8R_Gl-iiV9cUY) I could copy the CSS class they use and style the div element with that when the input element is focussed, which would mean I wouldn't need the condition to check if it's in dark mode. However this would require a separate CSS file in our repo. I can't use the exact same styling (import style from uppy somehow), because it would only apply when div is focussed, whilst I need it to apply when input is focussed.
> 
> _I did try and see if there was any way to trick the div element's CSS into think its being focussed, without actually focussing on it, but I couldn't find anything that worked_
> 
> _CSS also has the `focus-within` property which would be perfect for this case, since the input elem being triggered would cause any styling on the div with this as a condition to be applied, but again this would require changing the CSS class, which I don't think you can do using inline CSS, so it would also require a separate CSS stylesheet in our repo._
> 
> I tried passing the theme prop from the dashboard to the render function, however it does not update when I switch themes.
> 
> I think if I want to do uppy's implementation I would need to either: a. create a separate CSS file to create a CSS class in the same way uppy does, or b. use data-uppy-theme as the condition on whether it is dark (however it gets this from theme prop, which I also passed to my function, but it does not mutate).

Implement option B. Option A doesn’t align well with the coding style we use for defining CSS for elements.

2025-01-27 13:03 UTC, asuresh-code commented
> Implement option B. Option A doesn’t align well with the coding style we use for defining CSS for elements.

I've tried implementing this option, however the theme prop in the Render function does not update when the theme changes. It does update in the `uploadDialog` component, but not in the render function. 

I've tried passing it using React.useState and explicitly updating it in the parent component, but the change doesn't trickle down, and I can't call useTheme() to check the theme directly in the function since it is a React Hook and violates React Hook Laws by doing so.

2025-01-27 13:25 UTC, joshuadkitenge commented
> > Implement option B. Option A doesn’t align well with the coding style we use for defining CSS for elements.
> 
> I've tried implementing this option, however the theme prop in the Render function does not update when the theme changes. It does update in the `uploadDialog` component, but not in the render function.
> 
> I've tried passing it using React.useState and explicitly updating it in the parent component, but the change doesn't trickle down, and I can't call useTheme() to check the theme directly in the function since it is a React Hook and violates React Hook Laws by doing so.

This should be possible to do

2025-01-28 11:57 UTC, joshuadkitenge commented
> * As the metafields for attachements and images are the same can you make a general object to set them both

you have current done this for just the name this should be done the whole metafields @asuresh-code

2025-01-28 14:12 UTC, asuresh-code commented
> > * As the metafields for attachements and images are the same can you make a general object to set them both
> 
> you have current done this for just the name this should be done the whole metafields @asuresh-code
> 
> Hint: const { metafields } = useMetaFields();

I'm in the process of writing a function that generalises all of the metafields instead of just the filename field, and just wanted to check if `useMetaFields();` is an example name of the function and not an actual one that exists? I checked the uppy repo, and couldn't find an entry under that name?

2025-02-03 15:14 UTC, joshuadkitenge commented on src/common/editFileDialog.component.tsx
> +  const [initialName, extension] = splitFilename(selectedFile.file_name);
```suggestion
  const [initialName, extension] = getNameAndExtension(selectedFile.file_name);
```

2025-02-04 09:31 UTC, joshuadkitenge requested changes

2025-02-04 09:31 UTC, joshuadkitenge commented on src/common/attachments/uploadAttachmentsDialog.component.test.tsx
> +    await user.type(description, 'test description');
This approach using `getAllByRole('textbox')` is not ideal for accessibility. By relying only on the role and index, it becomes difficult to ensure that the correct input field is being interacted with.

2025-02-04 09:31 UTC, joshuadkitenge commented on src/common/editFileDialog.component.tsx
> +    resolver: zodResolver(FileSchemaPatch()),
The FileSchemaPatch() implementation here is unnecessary because FileSchemaPatch doesn't require any parameters or dynamic evaluation. Since it’s not a function or callable that needs to be invoked, it’s better to pass it directly to the resolver as `zodResolver(FileSchemaPatch)`.

2025-02-04 09:31 UTC, joshuadkitenge commented on src/common/uppy.utils.tsx
> +  '.custom-div-focus': {
The CSS class name custom-div-focus is too generic and could lead to potential naming clashes. To make it more descriptive and context-specific, consider including both ims and uppy in the class name, along with its purpose (focus state within an input).

2025-02-04 09:31 UTC, joshuadkitenge commented on src/common/uppy.utils.tsx
> +//Uppy custom type: MetaField[] type imported from node modules:
```suggestion
```
This is not needed.

2025-02-04 09:31 UTC, joshuadkitenge commented on src/form.schemas.tsx
> +  });
```suggestion
export const FileSchemaPatch = 
  z.object({
    file_name: MandatoryStringSchema({
      errorMessage: 'Please enter a file name.',
    }),
    title: NullableStringSchema,
    description: NullableStringSchema,
  });
```

2025-02-04 09:49 UTC, joshuadkitenge requested changes

2025-02-04 09:57 UTC, joshuadkitenge commented on src/common/images/uploadImagesDialog.component.test.tsx
> +    const [filename, title, _] = screen.getAllByRole('textbox');
same as above

2025-02-05 10:19 UTC, joshuadkitenge approved these changes

2025-02-05 10:25 UTC, merged