Download for images #1076
ral-facilities/inventory-management-system pull request #1220
Opened 2024-12-24 09:21 UTC by asuresh-code

## Description

Enter a description of the changes here

## Testing instructions

Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking

connect to {issue number}

2025-01-09 13:47 UTC, joshuadkitenge commented on src/common/images/uploadImagesDialog.component.tsx
> +          },
This should display the extension next to the text field please.

2025-01-13 11:10 UTC, joshuadkitenge commented on src/common/downloadFileDialog.component.tsx
> +  const handleDownloadImages = React.useCallback(() => {
This function should be general so it could work for images and attachments

2025-01-24 13:16 UTC, joshuadkitenge requested changes

2025-01-24 13:16 UTC, joshuadkitenge commented on src/common/downloadFileDialog.component.tsx
> +      document.body.appendChild(link);
Can you change this into a general component (downloadFile funciton) in the utils.tsx

2025-01-24 13:16 UTC, joshuadkitenge commented on src/common/images/deleteImageDialog.component.test.tsx
> -      entity_id: '2',
same as above

2025-01-24 13:16 UTC, joshuadkitenge commented on src/api/api.types.tsx
> +  download_url: string;
add a comment on what is different about these two urls and why is it being used in this way

2025-01-24 13:16 UTC, joshuadkitenge commented on src/common/images/imageGallery.component.tsx
> +    getRowId: (image) => image.id,
why was this added in ?

2025-01-24 13:16 UTC, joshuadkitenge commented on src/common/images/imageGallery.component.tsx
> +
use `setOpenMenuDialog` instead

2025-01-24 13:16 UTC, joshuadkitenge commented on src/common/images/imageGallery.component.tsx
> +                onClose={() => setdownloadImagesDialogOpen(false)}
same as above

2025-01-24 13:16 UTC, joshuadkitenge commented on src/common/images/uploadImagesDialog.component.test.tsx
> +
undo this change

2025-01-24 13:16 UTC, joshuadkitenge commented on src/common/images/uploadImagesDialog.component.tsx
> +          id: 'filename',
Why was this changed ??

2025-01-24 13:16 UTC, joshuadkitenge commented on src/systems/systemsLayout.component.test.tsx
> +
undo this change

2025-01-24 14:45 UTC, asuresh-code commented on src/api/images.tsx
> +    enabled: !!id,
Ah, that was leftover from when it was required to handle downloading multiple images.

2025-01-24 14:55 UTC, asuresh-code commented on src/common/images/uploadImagesDialog.component.tsx
> +          id: 'filename',
That was a change I forgot to undo when I moved the upload label implementation to the edit PR. That PR has id: set to name now.

2025-01-27 09:32 UTC, asuresh-code commented on src/common/images/imageGallery.component.tsx
> +    getRowId: (image) => image.id,
I believe that was also left over implemented from the multiple download implementation.

2025-01-28 10:48 UTC, joshuadkitenge requested changes

2025-01-28 10:48 UTC, joshuadkitenge commented on src/utils.tsx
> +}
This function should only need URL and filename.

2025-01-28 10:48 UTC, joshuadkitenge commented on src/common/downloadFileDialog.component.tsx
> +          onClick={handleDownloadFile}
The onClick should trigger the request for the download_url (GET request), instead of fetching it immediately (as it currently does on Line 39). Fetching it straight away can cause issues since the download_url has an expiry time. Additionally, it could result in unnecessary requests to the backend if the user accidentally leaves the dialog open.

2025-01-29 10:14 UTC, rowan04 commented on src/common/images/imageGallery.component.test.tsx
> +    expect(imageElement1).toBeInTheDocument();
apologies, my quite unclear point was, is the `toBeInTheDocument` needed if it is already found by `findByAltText`.

2025-01-29 11:07 UTC, asuresh-code commented on src/api/images.tsx
> +    enabled: !!id,
I've added enabled back into the implementation, since it's required to call the query only when the continue button is clicked.

The id for the query is provided by a state variable (originally set to an empty string). When continue is clicked, the state variable is set to the file.id, which triggers the query to activate since it is now provided with an id.

2025-01-29 12:36 UTC, joshuadkitenge requested changes

2025-01-29 12:36 UTC, joshuadkitenge commented on src/common/downloadFileDialog.component.tsx
> +  }, [downloadFile, error, handleDownloadFile, downloadIsPending]);
Instead of fetching data through the `useEffect`, use `QueryClient.fetchQuery` (https://tanstack.com/query/latest/docs/reference/QueryClient/#queryclientfetchquery). This approach minimizes the risk of errors related to the dependencies in the `useEffect` hook  and ensures more predictable behavior. This would probably require a redesign to find the most optimal solution for the this use case.

2025-01-30 11:12 UTC, joshuadkitenge requested changes

2025-01-30 11:12 UTC, joshuadkitenge commented on src/common/downloadFileDialog.component.tsx
> +    });
Why is the query being removed ?

2025-01-30 11:12 UTC, joshuadkitenge commented on src/common/downloadFileDialog.component.tsx
> +      });
https://github.com/ral-facilities/inventory-management-system/blob/f4453611510638bdb6023f428bffcbf69efb3a11/src/api/catalogueCategories.tsx#L476

use the method in the link for the query options so it is not defined twice

2025-01-30 11:12 UTC, joshuadkitenge commented on src/common/downloadFileDialog.component.tsx
> +      if (error instanceof CancelledError) closing = true;
Did you manage to trigger this error this when you manually testing it ? and if so how ??

2025-01-30 11:12 UTC, joshuadkitenge commented on src/common/downloadFileDialog.component.tsx
> +    try {
Can you use a `then` and ` catch` block please as we don't tend to use try and catch.

2025-01-30 11:12 UTC, joshuadkitenge commented on src/common/downloadFileDialog.component.tsx
> +  const handleDownloadFile = React.useCallback(
the handleClick and handleDownloadFile can be done in one function

2025-01-30 11:13 UTC, joshuadkitenge commented on src/common/images/imageGallery.component.tsx
> +                getFile={getImage}
This does not need to be past through as a prop. As it is only need when the dialog is open

2025-01-30 11:14 UTC, joshuadkitenge commented on src/common/images/imageGallery.component.tsx
> +                open={openMenuDialog == 'download'}
```suggestion
                open={openMenuDialog === 'download'}
```

2025-01-31 10:06 UTC, asuresh-code commented on src/common/downloadFileDialog.component.tsx
> +    });
If a get query is unresponsive (for example downloading the 5th image/image with id 5), it will refetch several times before finally erroring. Even if you close the dialog, the query will remain in flight, and will eventually throw an error that will appear when you next open a dialog.

Removing the query when you close the dialog cancels it, raising a `CancelledError` in the `handleClick` function. This error is caught and handled, preventing the `handleDownloadFile` function, therefore stopping the error from effecting the dialog error text.

2025-01-31 10:24 UTC, asuresh-code commented on src/common/downloadFileDialog.component.tsx
> +      if (error instanceof CancelledError) closing = true;
This error gets triggered when the dialog is closed by `queryClient.removeQueries` **IF** the query is still fetching/refetching when you close it.

I tested it by trying to download the 5th image in any gallery using mock data (since in the handlers, the 5th image always returns an error).

2025-01-31 10:55 UTC, joshuadkitenge commented on src/common/downloadFileDialog.component.tsx
> +    });
The get request should not retry, this can be altered in the react query options

2025-01-31 13:00 UTC, asuresh-code commented on src/common/downloadFileDialog.component.tsx
> +      if (error instanceof CancelledError) closing = true;
I've changed the implementation so that it does not retry. I've since removed this part of the implementation

2025-01-31 13:18 UTC, asuresh-code commented on src/common/images/imageGallery.component.tsx
> +                getFile={getImage}
I'm a bit confused, which prop are you referring to? Looking at it most of the props seem required, except for getFile which you could determine via the fileType in the dialog?

2025-01-31 13:38 UTC, joshuadkitenge commented on src/common/images/imageGallery.component.tsx
> +                getFile={getImage}
yeah just the getFile

2025-02-03 11:33 UTC, joshuadkitenge requested changes

2025-02-03 11:33 UTC, joshuadkitenge commented on src/api/images.tsx
> +export const getImageQuery = (id: string, loader?: boolean) =>
```suggestion
export const getImageQuery = (id: string, loader?: boolean) =>
```

Can you please rename the loader variable? It was specifically named this way in other functions to align with React Router loaders, but it should not be used in this case for clarity and to avoid confusion.

2025-02-03 11:33 UTC, joshuadkitenge commented on src/common/downloadFileDialog.component.tsx
> +  const getFile = fileType === 'Image' ? getImageQuery : getImageQuery;
```suggestion
  const getFile = fileType === 'Image' ? getImageQuery : getImageQuery;
```

`getFile` is not a descriptive enough name. Consider using a more specific name, such as `getDownloadFileQuery`. Additionally, this conditional statement is incorrect, you should set the other case explicitly or leave it as `undefined`. Alternatively, consider removing it entirely so it can be handled properly in the attachments PR.

`const getDownloadFileQuery =  getImageQuery`

2025-02-03 11:33 UTC, joshuadkitenge commented on src/common/downloadFileDialog.component.tsx
> +  const [isLoading, setIsLoading] = React.useState(false);
Loading is not needed for this dialog. This dialog should just close and the error handling should be dealt with by the `handleIMS_APIError` which displays the error as a toast

2025-02-03 11:33 UTC, joshuadkitenge commented on src/common/downloadFileDialog.component.tsx
> +        setFormError('No data provided. Please refresh and try again');
Remove this error message as it is not needed. It was used when the `selectedData` prop was optional, but that is not the case for this dialog. This could also lead to confusion, as the error message would not match the toast error in some instances.

2025-02-03 11:33 UTC, joshuadkitenge commented on src/common/downloadFileDialog.component.tsx
> +        <WarningIcon sx={{ marginRight: 1 }} />
Why is there a warning icon ??

2025-02-03 11:33 UTC, joshuadkitenge commented on src/common/downloadFileDialog.component.tsx
> +        data-testid="download-file-dialog-title"
Why is this `data-testid` needed? You should be able to find this using the standard `findBy*` methods from the React Testing Library instead.

2025-02-03 11:33 UTC, joshuadkitenge commented on src/common/downloadFileDialog.component.tsx
> +      <DialogContent data-testid="download-images-message">
same as above ??

2025-02-03 11:33 UTC, joshuadkitenge commented on src/common/downloadFileDialog.component.tsx
> +          endIcon={isLoading ? <CircularProgress size={20} /> : null}
These two line shouldn't be needed anymore look above

2025-02-03 11:33 UTC, joshuadkitenge commented on src/common/downloadFileDialog.component.tsx
> +      )}
These lines shouldn't be needed anymore look above

2025-02-03 12:22 UTC, asuresh-code commented on src/common/downloadFileDialog.component.tsx
> +        <WarningIcon sx={{ marginRight: 1 }} />
I think that was left over when I was basing the dialog from a delete dialog

2025-02-03 12:28 UTC, asuresh-code commented on src/common/downloadFileDialog.component.tsx
> +        data-testid="download-file-dialog-title"
Before the test was failing, because the text was broken up during the test checks. 

However, I just tried using findBy again, and the text is no longer broken up (made a few changes to the title since) , so I've changed it back to findBy.

2025-02-03 13:40 UTC, joshuadkitenge requested changes

2025-02-03 13:40 UTC, joshuadkitenge commented on src/common/downloadFileDialog.component.test.tsx
> +  let file: APIImage;
This is only used in one place. so doesn't need to be a `let`

2025-02-03 13:40 UTC, joshuadkitenge commented on src/common/downloadFileDialog.component.test.tsx
> +    file = ImagesJSON[0];
```suggestion
```

2025-02-03 13:40 UTC, joshuadkitenge commented on src/common/downloadFileDialog.component.test.tsx
> +      file: file,
```suggestion
      file: ImagesJSON[0],
```

2025-02-03 13:40 UTC, joshuadkitenge commented on src/common/downloadFileDialog.component.tsx
> +      ></Box>
```suggestion
```

2025-02-03 14:11 UTC, joshuadkitenge requested changes

2025-02-03 14:11 UTC, joshuadkitenge commented on src/utils.tsx
> +  document: Document,
```suggestion
```

2025-02-03 14:11 UTC, joshuadkitenge commented on src/common/downloadFileDialog.component.tsx
> +        downloadFileByLink(document, data.download_url, data.file_name);
```suggestion
        downloadFileByLink(data.download_url, data.file_name);
```

2025-02-03 14:38 UTC, joshuadkitenge commented
https://github.com/ral-facilities/object-storage-api/pull/94

2025-02-03 15:01 UTC, joshuadkitenge requested changes

2025-02-03 15:01 UTC, joshuadkitenge commented on src/common/downloadFileDialog.component.tsx
> +      <DialogTitle sx={{ display: 'inline-flex', alignItems: 'center' }}>
```suggestion
      <DialogTitle>
```

2025-02-03 16:49 UTC, joshuadkitenge approved these changes

2025-02-04 11:17 UTC, merged