Copy to catalogue item #178
ral-facilities/inventory-management-system pull request #185
Opened 2023-12-13 11:12 UTC by joshuadkitenge

## Description

A user should be able to copy a catalogue item to another catalogue category

## Testing instructions

Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] copy a catalogue to a new directory and the same 
- [ ] error states 
- [ ] {more steps here}

## Agile board tracking

connect to {issue number}

2024-01-02 16:46 UTC, MatteoGuarnaccia5 requested changes
Same thing as in #173 with the manufacturer in tests that should be`manufacturer_id`

2024-01-02 16:46 UTC, MatteoGuarnaccia5 commented on src/catalogue/items/catalogueItemDirectoryDialog.component.test.tsx
> +        manufacturer: {
should be `manufactuer_id` now

2024-01-02 16:46 UTC, MatteoGuarnaccia5 commented on src/catalogue/items/catalogueItemDirectoryDialog.component.test.tsx
> +        manufacturer: {
same here

2024-01-02 16:46 UTC, MatteoGuarnaccia5 commented on src/catalogue/items/catalogueItemDirectoryDialog.component.test.tsx
> +        manufacturer: {
same here

2024-01-02 16:46 UTC, MatteoGuarnaccia5 commented on src/catalogue/items/catalogueItemDirectoryDialog.component.test.tsx
> +        manufacturer: {
same here

2024-01-03 10:00 UTC, joelvdavies requested changes
Two minor comments, Apart from the query invalidation works well.

2024-01-03 11:22 UTC, MatteoGuarnaccia5 approved these changes
LGTM

2024-01-03 11:55 UTC, joelvdavies approved these changes

2024-01-03 12:22 UTC, merged