Save as system #137
ral-facilities/inventory-management-system pull request #205
Opened 2024-01-05 13:03 UTC by joelvdavies

## Description

- Adds a menu to each system/subsystem with edit, save as and delete (which has been removed from the landing page)
- Adds save as dialog

![image](https://github.com/ral-facilities/inventory-management-system/assets/90245114/89777fc5-a19a-41f0-a6f1-a8cc3dd62f4f)
![image](https://github.com/ral-facilities/inventory-management-system/assets/90245114/da7a33f3-c7bd-4862-87e1-a721098899ae)

## Testing instructions

Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking

Closes #137

2024-01-08 11:23 UTC, MatteoGuarnaccia5 reviewed
![image](https://github.com/ral-facilities/inventory-management-system/assets/144466888/4025e795-b095-4df1-857c-73017126accb)

When moving a system into another system, I found that the chosen system still remains visible, until you refresh the screen or click into the system it was moved into. Should probably refetch the systems after moved so that it displays the correct systems

2024-01-08 11:23 UTC, MatteoGuarnaccia5 commented on cypress/e2e/system.cy.ts
> +    it("save as a system eidting only a system's name (in subsystem)", () => {
```suggestion
    it("save as a system editing only a system's name (in subsystem)", () => {
```

2024-01-09 09:40 UTC, joshuadkitenge requested changes
Everything work well. Just one minor comment:

- can you make it so that when a user "save as" a system that the name defaults with `_copy_{iteration of the copy}`. Just so it matches the implementation done in catalogue items table view.

2024-01-09 11:50 UTC, joelvdavies commented
> Everything work well. Just one minor comment:
> 
> * can you make it so that when a user "save as" a system that the name defaults with `_copy_{iteration of the copy}`. Just so it matches the implementation done in catalogue items table view.

Just realised this is actually easier to resolve with the changes to use the table, I will just create conflicts here so I will make a note in the issue and do it there if that's alright (although I have just refactored slightly here to reduce code repetition)

2024-01-10 14:47 UTC, joshuadkitenge approved these changes

2024-01-10 14:54 UTC, merged