Edit item #13
ral-facilities/inventory-management-system pull request #249
Opened 2024-01-18 10:23 UTC by joshuadkitenge

## Description

allows the user to edit an item

## Testing instructions

Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking

closes #13

2024-01-19 15:10 UTC, joelvdavies requested changes
Just the query invalidation needs changing

2024-01-19 15:10 UTC, joelvdavies commented on cypress/e2e/items.cy.ts
> +  it('should display an error message there is an unknown error', () => {
```suggestion
  it('should display an error message if there is an unknown error', () => {
```

2024-01-19 15:10 UTC, joelvdavies commented on src/items/itemDialog.component.tsx
> +  >(undefined);
Can these not be the same state?

2024-01-22 10:23 UTC, joshuadkitenge commented
wait on https://github.com/ral-facilities/inventory-management-system-api/pull/152

2024-01-26 09:38 UTC, joelvdavies approved these changes
As mentioned on https://github.com/ral-facilities/inventory-management-system-api/pull/152#discussion_r1467369075 I think it would be nice to have placeholder text on on the create/edit dialog, but probably best as a separate issue anyway.

2024-01-26 09:45 UTC, merged