Error handling #262
ral-facilities/inventory-management-system pull request #275
Opened 2024-01-24 10:14 UTC by joshuadkitenge

## Description

- Add global error handler for the get requests
- remove console.log for the react query  functions 
  

## Testing instructions

Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking

closes #262

2024-01-26 10:33 UTC, joshuadkitenge commented
waiting on auth in the backend

2024-02-01 15:31 UTC, joshuadkitenge commented on src/handleIMS_APIError.ts
> +  const message = error.response?.data
Fix this

2024-02-02 11:44 UTC, joelvdavies requested changes
Two minor things, and some conflicts to resolve. Tested with https://github.com/ral-facilities/inventory-management-system-api/pull/169, error messages worked well and redirect to login when the token expires works as well.

2024-02-02 15:21 UTC, joshuadkitenge commented on src/catalogue/items/catalogueItemsDialog.component.test.tsx
> +      expect(handleIMS_APIError).toHaveBeenCalled();
The handleIMS_APIError components has the tests. The handleIMS_APIError is only for the uncaught errors (500)

2024-02-02 15:28 UTC, joshuadkitenge commented
Add error handling for the moveto and copyto

2024-02-02 15:32 UTC, joelvdavies commented on src/catalogue/items/catalogueItemsDialog.component.test.tsx
> +      expect(handleIMS_APIError).toHaveBeenCalled();
Yes but it doesn't check what it is sending handleIMS_APIError. It was more for ensuring the appropriate message and broadcast is sent and not something else, But then again none of them specify broadcast at the moment and the matcher for the error would probably have to be expect.anything() anyway, so its probably alright for now.

2024-02-05 10:23 UTC, joshuadkitenge commented
do the todos in the api functions

2024-02-08 16:54 UTC, joshuadkitenge commented
I copy loads of catalogue categories and then I was trying to delete them it done this when it triggered a refresh @joelvdavies 


![error handle bug](https://github.com/ral-facilities/inventory-management-system/assets/83226114/448a6d22-a4a7-47d0-b8e0-3df4cecfa509)

2024-02-13 14:39 UTC, VKTB requested changes
The requests to the `/units` API endpoint fail with `403 Not authenticated`. I think that the JWT access token is not supplied.

2024-02-21 08:34 UTC, VKTB approved these changes

2024-02-21 08:36 UTC, joelvdavies approved these changes

2024-02-21 08:36 UTC, merged