add catalogue list catalogue item property type #220
ral-facilities/inventory-management-system pull request #276
Opened 2024-01-25 13:15 UTC by joshuadkitenge

## Description
add the list type to the catalogue item properties 

## Testing instructions

Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] test the error handling

## Agile board tracking

closes #220

2024-01-31 11:02 UTC, joelvdavies reviewed
Some minor things for the moment, haven't gone through all yet, but worked well when I tested it.

2024-01-31 11:50 UTC, joshuadkitenge commented on src/catalogue/category/catalogueCategoryDialog.component.tsx
> +    const validateCatalogueItems = (
Give this a better name

2024-01-31 11:57 UTC, joshuadkitenge commented on src/catalogue/category/catalogueCategoryDialog.component.tsx
> +            Array.from(new Set(invalidNumberIndexes)).length > 0 ||
remove set fromm the invalid number and missing value

2024-01-31 11:59 UTC, joshuadkitenge commented on src/catalogue/category/catalogueCategoryDialog.component.tsx
> +
Order dependent

2024-01-31 11:59 UTC, joshuadkitenge commented on src/catalogue/category/catalogueCategoryDialog.component.tsx
> +                  ...Array.from(new Set(invalidNumberIndexes)).map((i) => ({
remove the set. look above

2024-01-31 12:02 UTC, joshuadkitenge commented on src/catalogue/category/catalogueCategoryDialog.component.tsx
> +      if (catalogueItemPropertiesErrors.length !== 0 || formFieldErrors) {
remove catalogueItemPropertiesErrors.length !== 0

2024-01-31 12:22 UTC, joshuadkitenge commented on src/catalogue/category/cataloguePropertiesForm.component.tsx
> +
add comment (this clears "Please create a valid list item")

2024-01-31 12:28 UTC, joshuadkitenge commented on src/catalogue/category/cataloguePropertiesForm.component.tsx
> +  const isError = React.useCallback(
hasFieldError

2024-01-31 12:32 UTC, joshuadkitenge commented on src/catalogue/category/cataloguePropertiesForm.component.tsx
> +  const listErrorMessage = React.useCallback(
allowedValuesListError

2024-02-01 16:39 UTC, joelvdavies requested changes
Just a last few minor things

2024-02-01 16:39 UTC, joelvdavies commented on src/catalogue/category/catalogueCategoryDialog.component.tsx
> +            // The set removes the repeated indexes.
This comment should be above the line above

2024-02-01 16:39 UTC, joelvdavies commented on src/catalogue/category/cataloguePropertiesForm.component.test.tsx
> +  it('display error if duplicate property names are entered and clears when a name is change', async () => {
```suggestion
  it('display error if duplicate property names are entered and clears when a name is changed', async () => {
```

2024-02-01 16:39 UTC, joelvdavies commented on src/catalogue/category/cataloguePropertiesForm.component.test.tsx
> +  it('should add a list item when the add icon is click', async () => {
```suggestion
  it('should add a list item when the add icon is clicked', async () => {
```

2024-02-01 16:39 UTC, joelvdavies commented on src/catalogue/category/cataloguePropertiesForm.component.test.tsx
> +  it('should edit a list item when the add icon is click', async () => {
```suggestion
  it('should edit a list item when the add icon is clicked', async () => {
```

2024-02-01 16:39 UTC, joelvdavies commented on src/catalogue/category/cataloguePropertiesForm.component.test.tsx
> +  it('should error for duplicate values and incorrect type values and the error should be remove if catalogue item property is deleted', async () => {
```suggestion
  it('should display error for duplicate values and incorrect type values and the error should be removed if the catalogue item property is deleted', async () => {
```

2024-02-01 16:39 UTC, joelvdavies commented on src/catalogue/category/cataloguePropertiesForm.component.test.tsx
> +  it('should error for incorrect type values and remove error if the value has been deleted', async () => {
```suggestion
  it('should display error for incorrect type values and remove the error if the value has been deleted', async () => {
```

2024-02-01 16:39 UTC, joelvdavies commented on src/catalogue/category/cataloguePropertiesForm.component.test.tsx
> +  it('should error for duplicate values and incorrect type values and the error should be if the type has changed', async () => {
```suggestion
  it('should display error for duplicate values and incorrect type values and the error should be removed if the type is changed', async () => {
```

2024-02-02 09:50 UTC, joelvdavies approved these changes

2024-02-02 10:53 UTC, merged