Notes to catalogue item #264
ral-facilities/inventory-management-system pull request #286
Opened 2024-01-30 10:38 UTC by MatteoGuarnaccia5

## Description

Implement notes for catalogue items. Added tooltip to item dialog as well which shows the parent catalogue item note.

## Testing instructions

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
## Agile board tracking

closes #264

2024-01-31 09:54 UTC, joshuadkitenge commented
> Just some minor things.
> 
> @joshuadkitenge I noticed we allow multiline notes in text boxes, but always condense them into one line when displaying them elsewhere, I think its fine as it is for now but thought I should mention it - I think it would be tricky for tooltips anyway.

Is this going to be a problem for the normal text being rendered in the table (if it is too long) ?   @joelvdavies

2024-01-31 10:00 UTC, joshuadkitenge commented on src/items/itemDialog.component.test.tsx
> +          screen.getByLabelText('Catalogue item note: null')
Yeah I think for now it simplest to return "None" ('Catalogue item note: None').

2024-01-31 10:15 UTC, joshuadkitenge commented
> > > Just some minor things.
> > > @joshuadkitenge I noticed we allow multiline notes in text boxes, but always condense them into one line when displaying them elsewhere, I think its fine as it is for now but thought I should mention it - I think it would be tricky for tooltips anyway.
> > 
> > 
> > Is this going to be a problem for the normal text being rendered in the table (if it is too long) ? @joelvdavies
> 
> Yes we don't prevent long names and replace them with tooltips anywhere so technically they could all display tonnes of text (not that I would expect extremely long fields everywhere), I only meant the notes field in the comment as you can write a note like
> 
> ```
> Some
> 
> notes
> ```
> 
> Which then gets displayed as `Some notes` on the landing page/in the tooltips.

Adding this` whiteSpace: 'pre-line'` to the sx prop should sort out that problem.

2024-01-31 10:19 UTC, joshuadkitenge requested changes
Works well. Could you please add whiteSpace: 'pre-line' for all descriptions and notes (obsolete reason) displayed throughout the website any other multiline content

2024-02-01 10:18 UTC, joshuadkitenge approved these changes

2024-02-01 15:56 UTC, joelvdavies approved these changes

2024-02-01 16:03 UTC, merged