Add button for directory dialogs #192
ral-facilities/inventory-management-system pull request #347
Opened 2024-02-27 13:58 UTC by MatteoGuarnaccia5

## Description

Enter a description of the changes here

## Testing instructions

Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking

connect to {issue number}

2024-02-27 16:58 UTC, joelvdavies commented on src/catalogue/category/catalogueCategoryTableView.component.tsx
> +          />
I think these coverage warnings can be resolved if they were tested in the unit tests. There is another for the systems table view.

2024-02-28 09:38 UTC, joshuadkitenge requested changes
Works nicely, just a couple of comments.

- Can you make the size of the dialogs bigger so there is no vertical scroll bar 

- Also I think it makes more sense for the add button in the catalogue item directory dialog to be use the "save as" functionality as the catalogue item properties needs to be identical for a user to transfer the catalogue item 

- Remove the add catalogue item button in moveTo and copyTo

2024-03-01 12:40 UTC, joshuadkitenge approved these changes
LGTM

2024-03-01 15:57 UTC, joelvdavies submitted a review, later dismissed

2024-03-02 18:59 UTC, joshuadkitenge approved these changes

2024-03-02 19:14 UTC, merged