changed table to use system name and not id #497
ral-facilities/inventory-management-system pull request #505
Opened 2024-04-16 13:15 UTC by MatteoGuarnaccia5

## Description

Changed items table to display system name rather than system ID. 
System objects are fetched from backend from set of system IDs - set of IDs is created from items data

## Testing instructions

Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage

## Agile board tracking

closes #497

2024-04-18 10:13 UTC, joelvdavies commented on src/api/systems.tsx
> +export const useSystemIds = (ids: string[]): UseQueryResult<System>[] => {
I think this should have a unit test like `useCatalogueItemIds`/`useManufacturerIds`

2024-04-23 09:38 UTC, joelvdavies requested changes
Two minor comments. Also could you update the landing pages and detail panels to use system name as well please.

I also noticed that navigating using the system name link from the items table to a systems page causes
![image](https://github.com/ral-facilities/inventory-management-system/assets/90245114/b279312d-65e8-4292-b886-28dcd8d29c6c)

2024-04-23 09:43 UTC, joshuadkitenge commented
Can the system be grouped by the system id and not the name please

2024-05-01 10:07 UTC, joelvdavies approved these changes
LGTM

2024-05-07 08:47 UTC, merged