added route for admin #533
ral-facilities/inventory-management-system pull request #535
Opened 2024-05-01 12:10 UTC by MatteoGuarnaccia5

## Description

Enter a description of the changes here

## Testing instructions

Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking

connect to {issue number}

2024-05-16 12:09 UTC, joelvdavies reviewed
Just minor suggestions.

2024-05-17 14:02 UTC, joshuadkitenge requested changes

2024-05-20 08:14 UTC, joshuadkitenge requested changes

2024-05-20 08:14 UTC, joshuadkitenge commented on src/App.tsx
> +  admin: '/admin-ims',
```suggestion
  admin: '/admin-ims/*',
```

2024-05-20 08:14 UTC, joshuadkitenge commented on src/App.tsx
> +  usageStatus: '/admin-ims/usage-status',
```suggestion
```

2024-05-20 08:14 UTC, joshuadkitenge commented on src/App.tsx
> +      { path: paths.usageStatus, Component: AdminPage },
```suggestion
      { path: paths.admin, Component: AdminPage },
```

2024-05-20 08:50 UTC, joshuadkitenge commented on src/admin/admin.component.tsx
> +
can the breadcrumbs be "Units" and "Usage status". it is currently "units" and  "usage-status" 

`
adminBreadcrumbs = {['units']:'Units',['usage-status']:'Usage status'}`

2024-05-20 10:14 UTC, joelvdavies requested changes

2024-05-20 10:14 UTC, joelvdavies commented on src/admin/admin.component.tsx
> +                        <Typography>Usage Status</Typography>
```suggestion
                        <Typography>Usage Statuses</Typography>
```
Could the names be changed to `Usage statuses` and `usage-statuses` to match units please.

2024-05-20 10:14 UTC, joelvdavies commented on src/admin/admin.component.tsx
> +      {adminPageName === 'usage-status' && <UsageStatus />}
```suggestion
      {adminPageName === 'usage-statuses' && <UsageStatuses />}
```

2024-05-20 13:28 UTC, joelvdavies commented on src/admin/usageStatus.component.tsx
Could you rename this file to usageStatuses as well please.

2024-05-20 14:47 UTC, joshuadkitenge requested changes
https://github.com/ral-facilities/inventory-management-system/assets/83226114/08b9d999-0aea-4d2f-80f4-9fb93f9dd3e0

the breadcrumbs alignment is off compared to the other pages

2024-05-20 14:56 UTC, joshuadkitenge commented on src/admin/admin.component.tsx
> +
can you use a dictionary to assign the user friendly names please 
`adminBreadcrumbsNames[adminPageName ?? '']`

2024-05-20 15:01 UTC, joshuadkitenge requested changes
![image](https://github.com/ral-facilities/inventory-management-system/assets/83226114/4dfed020-27eb-4fdd-b566-f10c650222e6)

add no results page please for an invalid url

2024-05-21 09:42 UTC, joshuadkitenge commented on src/admin/admin.component.tsx
> +              screen.
```suggestion
The admin URL route you're trying to access doesn't exist. Please return to the homepage by clicking the home button  at the top left of your screen.
```

2024-05-21 09:45 UTC, joshuadkitenge commented on src/admin/admin.component.tsx
> +  const adminBreadCrumbsNames: { [key: string]: [string, string] } = {
```suggestion
  const adminBreadCrumbsTrails: { [key: string]: [string, string] } = {
```

Can this also be defined outside of the component function please

2024-05-21 09:52 UTC, joshuadkitenge commented on src/admin/admin.component.tsx
> +    ['usage-statuses']: ['Usage statuses', 'Usage statuses'],
```suggestion
    ['units']: ['units', 'Units'],
    ['usage-statuses']: ['usage-statuses', 'Usage statuses'],
```

2024-05-21 09:53 UTC, joshuadkitenge commented
![image](https://github.com/ral-facilities/inventory-management-system/assets/83226114/ca2f8ea9-8bfe-473d-bffd-7dab473146de)
the no result page appears on the admin home page

2024-05-21 09:56 UTC, joshuadkitenge commented on src/admin/admin.component.tsx
> +      {adminPageName !== undefined &&
```suggestion
      {adminPageName !== null &&
```

2024-05-21 09:57 UTC, joshuadkitenge commented on src/admin/admin.component.tsx
> +      {adminPageName !== undefined &&
This should stop the no results message from appearing on the admin home page

2024-05-21 14:54 UTC, joshuadkitenge approved these changes
LGTM

2024-05-21 15:18 UTC, joelvdavies approved these changes

2024-05-22 08:49 UTC, merged