Crd for units #536
ral-facilities/inventory-management-system pull request #542
Opened 2024-05-07 10:46 UTC by MatteoGuarnaccia5

## Description

Enter a description of the changes here

## Testing instructions

Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking

connect to {issue number}

2024-05-16 10:34 UTC, MatteoGuarnaccia5 commented
api e2e tests pass locally - requires [#256 to be merged in on the backend](https://github.com/ral-facilities/inventory-management-system-api/pull/256)

2024-05-22 14:30 UTC, joelvdavies commented on .github/workflows/ci-build.yml
In case I forget later, just a note to remove `python ./scripts/dev_cli.py --ci db-import` as it shouldn't need to import anything anymore.

2024-05-24 08:45 UTC, joelvdavies requested changes

2024-05-24 08:54 UTC, joshuadkitenge requested changes

2024-05-24 08:54 UTC, joshuadkitenge commented on src/admin/units/unitsDialog.component.tsx
> +              sx={{ marginLeft: '4px', my: '8px' }} // Adjusted the width and margin
```suggestion
              sx={{ marginLeft: '4px', my: '8px' }}
```

2024-05-24 08:54 UTC, joshuadkitenge commented on src/app.types.tsx
>  }
```suggestion
export interface AddUnit {
  value: string;
}

export interface Unit extends AddUnit {
  id: string;
  code:string;
  created_time: string;
  modified_time: string;
}


```

2024-05-24 08:54 UTC, joshuadkitenge commented on src/catalogue/category/cataloguePropertiesForm.component.test.tsx
> +        unit_id: undefined,
```suggestion
```

2024-05-24 08:54 UTC, joshuadkitenge commented on src/catalogue/category/cataloguePropertiesForm.component.test.tsx
> +        unit_id: undefined,
```suggestion
```

2024-05-24 08:54 UTC, joshuadkitenge commented on src/catalogue/category/cataloguePropertiesForm.component.test.tsx
> +        unit_id: undefined,
```suggestion
```

2024-05-24 08:54 UTC, joshuadkitenge commented on src/catalogue/category/cataloguePropertiesForm.component.test.tsx
> +        unit_id: undefined,
```suggestion
```

2024-05-24 08:54 UTC, joshuadkitenge commented on src/catalogue/category/cataloguePropertiesForm.component.test.tsx
> +        unit_id: undefined,
```suggestion
```

2024-05-24 08:54 UTC, joshuadkitenge commented on src/catalogue/category/cataloguePropertiesForm.component.test.tsx
> +        unit_id: undefined,
```suggestion
```

2024-05-24 08:54 UTC, joshuadkitenge commented on src/catalogue/category/cataloguePropertiesForm.component.test.tsx
> +          unit_id: undefined,
```suggestion
```

2024-05-24 08:54 UTC, joshuadkitenge commented on src/catalogue/category/cataloguePropertiesForm.component.test.tsx
> +        unit_id: undefined,
```suggestion
```

2024-05-24 08:54 UTC, joshuadkitenge commented on src/catalogue/category/cataloguePropertiesForm.component.test.tsx
> +        unit_id: undefined,
```suggestion
```

2024-05-24 08:54 UTC, joshuadkitenge commented on src/catalogue/category/cataloguePropertiesForm.component.test.tsx
> +        unit_id: undefined,
```suggestion
```

2024-05-24 08:54 UTC, joshuadkitenge commented on src/catalogue/category/cataloguePropertiesForm.component.test.tsx
> +        unit_id: undefined,
```suggestion
```

2024-05-24 08:54 UTC, joshuadkitenge commented on src/catalogue/category/cataloguePropertiesForm.component.test.tsx
> +        unit_id: undefined,
if unit_id is undefined you don't need it in the object

2024-05-24 08:56 UTC, joelvdavies requested changes

2024-05-24 08:56 UTC, joelvdavies commented on src/api/catalogueCategories.test.tsx
useMoveToCatalogueCategory, useCopyToCatalogueCategory and useAddCatalogueCategoryProperty are also missing `unit_id`s.

2024-05-24 08:56 UTC, joelvdavies commented on src/api/catalogueItems.test.tsx
`useMoveToCatalogueItem` and `useCopyToCatalogueItem` are also missing `unit_id`s.

2024-05-24 10:19 UTC, joelvdavies reviewed
Last few comments, worked well for me though.

2024-05-24 10:19 UTC, joelvdavies commented on src/catalogue/category/catalogueItemPropertiesMigrationDialog.component.test.tsx
There are still some `unit:` in this file with errors.

2024-05-24 10:19 UTC, joelvdavies commented on src/catalogue/category/catalogueCategoryDialog.component.test.tsx
There are still some `unit:`'s in this file with errors.

2024-05-24 10:19 UTC, joelvdavies commented on src/admin/units/deleteUnitsDialog.component.test.tsx
> +  it('calls handleDeleteSession when continue button is clicked with a valid session name', async () => {
I don't think this name makes sense. I think there are a few others if you search for `valid session name` could you change those as well please.

2024-05-28 12:28 UTC, MatteoGuarnaccia5 commented on src/catalogue/category/catalogueItemPropertiesMigrationDialog.component.test.tsx
I left them on purpose as they are all within the modifyValues function, so you want to pass through the value of the unit so it can be selected. So I thought it made sense to leave it as just unit not unit_id

2024-05-29 09:53 UTC, joelvdavies commented on src/catalogue/category/catalogueItemPropertiesMigrationDialog.component.test.tsx
> +  interface testCatalogueCategoryPropertyMigration
```suggestion
  interface TestCatalogueCategoryPropertyMigration
```

2024-05-29 09:53 UTC, joelvdavies commented on src/catalogue/category/cataloguePropertiesForm.component.test.tsx
> +
```suggestion
```

2024-05-29 09:53 UTC, joelvdavies commented on src/catalogue/category/cataloguePropertiesForm.component.test.tsx
> +
```suggestion
```

2024-05-29 09:53 UTC, joelvdavies commented on src/catalogue/category/cataloguePropertiesForm.component.test.tsx
> +
```suggestion
```

2024-05-29 09:53 UTC, joelvdavies commented on src/catalogue/category/cataloguePropertiesForm.component.test.tsx
> +
```suggestion
```

2024-05-29 09:53 UTC, joelvdavies commented on src/catalogue/category/cataloguePropertiesForm.component.test.tsx
> +
```suggestion
```

2024-05-29 09:53 UTC, joelvdavies commented on src/catalogue/category/cataloguePropertiesForm.component.test.tsx
> +
```suggestion
```

2024-05-29 09:58 UTC, joelvdavies commented on src/catalogue/category/catalogueCategoryDialog.component.test.tsx
> +  interface testAddCatalogueCategoryProperty
```suggestion
  interface TestAddCatalogueCategoryProperty
```

2024-05-29 13:00 UTC, joelvdavies commented on src/catalogue/category/cataloguePropertiesForm.component.test.tsx
> +
Just one missed.

2024-05-29 13:34 UTC, joelvdavies commented on src/catalogue/category/cataloguePropertiesForm.component.test.tsx
> +
This was missed

2024-05-30 08:31 UTC, joelvdavies commented on src/catalogue/category/cataloguePropertiesForm.component.test.tsx
> +
@MatteoGuarnaccia5 This is still here

2024-05-30 10:20 UTC, joshuadkitenge requested changes
Works well, just a few minor comments 

The heights of the units and usages statuses tables are still wrong 

 
![image](https://github.com/ral-facilities/inventory-management-system/assets/83226114/617e719e-6182-4eb2-b90b-ce531039fe75)

2024-05-30 10:20 UTC, joshuadkitenge commented on src/admin/units/units.component.tsx
> +    enableColumnResizing: true,
```suggestion
```

2024-05-30 10:20 UTC, joshuadkitenge commented on src/admin/units/units.component.tsx
> +    enableColumnResizing: true,
Can you also remove this from the usages statues table as well please. This would allow the columns to fill up the whole screen

2024-05-31 08:19 UTC, joelvdavies submitted a review, later dismissed
LGTM - Don't merge until we have it running on dev.

2024-05-31 08:34 UTC, joshuadkitenge approved these changes

2024-05-31 13:41 UTC, joelvdavies approved these changes

2024-05-31 14:29 UTC, joelvdavies approved these changes

2024-05-31 14:31 UTC, merged