Run fast pass on ims #507
ral-facilities/inventory-management-system pull request #595
Opened 2024-05-30 08:02 UTC by MatteoGuarnaccia5

## Description

Ran fastPass on IMS

## Testing instructions

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking

closes #507

2024-05-30 08:04 UTC, MatteoGuarnaccia5 commented
waiting on #525 and #542 to continue progress

2024-06-12 07:03 UTC, joshuadkitenge commented
Do this on Dev instance

2024-06-20 07:24 UTC, joshuadkitenge commented on src/catalogue/items/catalogueItemsDialog.component.tsx
> +                            aria-label={`${property.name} tooltip`}
```suggestion
                            aria-label={`${property.name} details`}
```

2024-06-20 07:26 UTC, joshuadkitenge commented on src/view/breadcrumbs.component.tsx
> +        separator={<NavigateNext fontSize="small" aria-label="navigate next" />}
```suggestion
        separator={<NavigateNext fontSize="small" />}
```

Is this still needed ???

2024-06-20 08:47 UTC, joshuadkitenge submitted a review, later dismissed

2024-06-20 13:04 UTC, joelvdavies requested changes
Just one minor thing, looks good otherwise.

2024-06-20 15:12 UTC, joshuadkitenge approved these changes

2024-06-21 07:49 UTC, joelvdavies approved these changes

2024-06-21 07:57 UTC, merged