Preserving table filters fixes #597
ral-facilities/inventory-management-system pull request #603
Opened 2024-05-31 11:13 UTC by joelvdavies

## Description

See #597

- Fixes bug where min/max filters wouldn't be removed from the URL when they were cleared

## Testing instructions

Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage

## Agile board tracking

Closes #597

2024-06-04 14:19 UTC, MatteoGuarnaccia5 reviewed
LGTM - just one thing

2024-06-04 14:19 UTC, MatteoGuarnaccia5 commented on src/common/preservedTableState.component.test.tsx
>        // console.log(
is the `console.log` needed?

2024-06-05 10:12 UTC, MatteoGuarnaccia5 approved these changes
Works well for me

2024-06-07 09:47 UTC, joshuadkitenge requested changes
the fix for #610   works well.

I found this bug for date range filters 

https://github.com/ral-facilities/inventory-management-system/assets/83226114/e77ef6d9-a668-48f9-ab96-b46cf21f95e2




I have also noticed that some weird behavior with the range filters in MRT. this a MRT problem.  I've create another issue for this to add custom error handling.#634
![image](https://github.com/ral-facilities/inventory-management-system/assets/83226114/547fb0fb-6338-4463-a4b8-72530f21731d)

2024-06-07 14:27 UTC, merged