Assess text overflow #567
ral-facilities/inventory-management-system pull request #620
Opened 2024-06-05 11:43 UTC by joshuadkitenge

## Description
see #567

## Testing instructions

Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking

closes #567

2024-06-11 10:22 UTC, MatteoGuarnaccia5 requested changes
![image](https://github.com/ral-facilities/inventory-management-system/assets/144466888/ddbd0522-e04f-4833-86a5-45d76b5068a8)

The landing pages need the overflow as well otherwise this occurs. This is items but I assume the same could occur elsewhere

2024-06-11 14:25 UTC, joshuadkitenge commented
> ![image](https://private-user-images.githubusercontent.com/144466888/338542533-ddbd0522-e04f-4833-86a5-45d76b5068a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTU2ODksIm5iZiI6MTcxODExNTM4OSwicGF0aCI6Ii8xNDQ0NjY4ODgvMzM4NTQyNTMzLWRkYmQwNTIyLWUwNGYtNDgzMy04NmE1LTQ1ZDc2YjUwNjhhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQxNDE2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzUxZTE4OTI5YjIwMWZjOWJmY2RjNDJiZWM1NGUxZTU3YTM1YWYzMmQwZDU5ZDdjNjYwZDIzYzBmYWY2NDA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xxKYT4stJsD7AUk34fV-3AERyh-sBo43VgmwQPq8Woc)
> 
> The landing pages need the overflow as well otherwise this occurs. This is items but I assume the same could occur elsewhere

This would not use the overflow. The text wrapping on the page is wrong

2024-06-11 15:15 UTC, joelvdavies approved these changes

2024-06-12 09:04 UTC, joelvdavies approved these changes

2024-06-12 09:06 UTC, MatteoGuarnaccia5 approved these changes

2024-06-12 09:27 UTC, merged