Add manufacturers #68
ral-facilities/inventory-management-system pull request #80
Opened 2023-09-28 10:47 UTC by MatteoGuarnaccia5

## Description

Add a manufacturer via a text form, all the fields need to be filled and there is relevant error checks (for invalid urls and duplicate names as well)

## Testing instructions

Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] test adding and also using invalid url, empty strings(spaces) =

## Agile board tracking

closes #68

2023-11-07 15:26 UTC, joelvdavies requested changes
A couple of things I noticed - With the exception of the missing grid elements (and console.log), I am happy for the other changes to be addressed in #112 if you prefer.

2023-11-07 16:18 UTC, joelvdavies commented on src/api/manufacturer.tsx
> +export const useAddManufacturer = (): UseMutationResult<
Addressed in https://github.com/ral-facilities/inventory-management-system/pull/97

2023-11-07 16:20 UTC, joelvdavies commented on src/manufacturer/manufacturerDialog.component.tsx
> +    React.useState<string | undefined>(undefined);
Should be addressed in https://github.com/ral-facilities/inventory-management-system/pull/112

2023-11-07 16:20 UTC, joelvdavies commented on src/manufacturer/manufacturerDialog.component.tsx
> +  const [URlerror, setURLError] = React.useState(false);
Should be addressed in https://github.com/ral-facilities/inventory-management-system/pull/112

2023-11-07 16:23 UTC, joelvdavies commented on src/app.types.tsx
> +}
Should be addressed in https://github.com/ral-facilities/inventory-management-system/pull/112

2023-11-07 16:23 UTC, joelvdavies commented on src/app.types.tsx
> +}
Should be addressed in https://github.com/ral-facilities/inventory-management-system/pull/118

2023-11-07 16:24 UTC, joelvdavies commented on src/manufacturer/manufacturerDialog.component.tsx
> +
Should be addressed in https://github.com/ral-facilities/inventory-management-system/pull/112

2023-11-07 16:25 UTC, joelvdavies commented on src/manufacturer/manufacturerDialog.component.tsx
> +    };
Should be addressed in https://github.com/ral-facilities/inventory-management-system/pull/112

2023-11-07 16:26 UTC, joelvdavies approved these changes
Should be merged with https://github.com/ral-facilities/inventory-management-system/pull/80.

2023-11-07 16:29 UTC, MatteoGuarnaccia5 commented on src/manufacturer/manufacturerDialog.component.tsx
> +  const [URlerror, setURLError] = React.useState(false);
addressed in #112 as 'add manufacturer changes' commit

2023-11-07 16:29 UTC, MatteoGuarnaccia5 commented on src/manufacturer/manufacturerDialog.component.tsx
> +    React.useState<string | undefined>(undefined);
addressed in #112 as 'add manufacturer changes' commit

2023-11-07 16:29 UTC, MatteoGuarnaccia5 commented on src/manufacturer/manufacturerDialog.component.tsx
> +    };
addressed in #112 as 'add manufacturer changes' commit

2023-11-07 17:04 UTC, joshuadkitenge commented on src/manufacturer/manufacturerDialog.component.tsx
> +  >(undefined);
That's a good suggestion. Could you create an issue so we can track these changes please. I'm going to change this in my updated catalogue items fields pr

2023-11-08 09:29 UTC, MatteoGuarnaccia5 commented on src/manufacturer/manufacturerDialog.component.tsx
> +  >(undefined);
Addressed in #118 PR with commit name 'change errors to use less states'

2023-11-08 10:07 UTC, merged

2023-11-08 10:50 UTC, MatteoGuarnaccia5 commented on src/app.types.tsx
> +}
addressed in #118 with commit name 'changed types to be | null'

2023-11-08 10:51 UTC, MatteoGuarnaccia5 commented on src/app.types.tsx
> +}
addressed in https://github.com/ral-facilities/inventory-management-system/pull/118 with commit name 'changed types to be | null'