Apply changes from OG Vite migration
ral-facilities/inventory-management-system pull request #817
Opened 2024-07-29 08:15 UTC by joelvdavies

## Description

Applies tweaks found while doing the OG Vite migration. Likely want the same changes on SciGateway's Vite branch too.

Draft as migration ongoing.

## Testing instructions

Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage

## Agile board tracking

2024-09-02 10:16 UTC, joelvdavies commented
Should only be merged when https://github.com/ral-facilities/operationsgateway/pull/421 is.

2024-09-06 10:24 UTC, joshuadkitenge requested changes
Works well with scigateway (preview:build:dev and preview:build). Just one minor comment

2024-09-06 10:40 UTC, joelvdavies commented on src/main.tsx
> +// TODO: Add tests for this like OG?
I will just remove the todo, I just added them in but it also adds a warning to the tests due to it still trying to fetch settings before msw is setup.

2024-09-06 11:09 UTC, joshuadkitenge approved these changes

2024-09-06 11:45 UTC, merged